### ISSUE TITLE
User lacks permission to update MeasuredTemplate error

### ISSUE THREAD

**Issue by napolitanod** [vtt-lair/simbuls-template-scaling#2]
Foundry: v10 291
DnD5e: 2.0.3
Simbul's Template: 1.0.0
Simbul's Athenaeum: 1.0.2
No other modules enabled (aside from the 2 above)

When placing a measured template that targets a PC, the player who owns that PC gets an error something like the below. (The 'update-queue' js is from Simbuls):

update-queue.js:43 Error: User TestUser lacks permission to update MeasuredTemplate [JyrBTE4TT2hkSr60] in parent Scene [I9NJ1vhwZ2OSIE2v]
    at ServerDatabaseBackend._updateEmbeddedDocuments (/home/ec2-user/foundry/resources/app/dist/database/backend/server-backend.mjs:1:4556)
    at async Semaphore._try (/home/ec2-user/foundry/resources/app/common/utils/semaphore.mjs:101:17)
runUpdate @ update-queue.js:43

To recreate:

Set the template scaling to 'All Templates'
1. Sign in as a GM and as a player in a second session (in this instance it is a 'Trusted Player').
2. Pull from dnd5e compendium the Ice Mephit and place that on the scene along with the signed in player's PC that they are owner of.
3. Use the Ice Mephit 'Frost Breath' ability, placing the cone template so that it targets the signed in player's character.
4. User's session will get a red error message for lacking permission to update template.

**Comment by vtt-lair** [comment]
Thanks. There was some changes to permissions and what is allowed in v10. Will see what I can do here.

**Comment by vtt-lair** [comment]
This has been fixed in the latest release @napolitanod
